### ISSUE TITLE
namedExports database

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-commonjs#125]
This might be a terrible idea, but just going to throw it out there...

It seems one of the big roadblocks for people switching to Rollup is that they expect named exports from CommonJS modules to Just Work, but they often don't because of the tendency among CommonJS authors to export properties in a way that can't be statically analysed.

For one thing, we need to make the resulting compile-time error message much clearer (though that's a job for Rollup itself, not this plugin).

But another thing we could potentially do is have a community-supported database of named exports for different versions of various libraries – so if we detected that the user was importing Immutable, say, we could automatically populated `namedExports.immutable` with

``` js
['Iterable', 'Seq', 'Collection', 'Map', 'OrderedMap', 'List', 'Stack', 'Set', 'OrderedSet', 'Record', 'Range', 'Repeat', 'is', 'fromJS']
```

and so on.

**Comment by sheerun** [comment]
Maybe we could extract exports from imports instead? Say module defines two files:

main.js
```
function awesome() { return 'awesomeName'; }
module.exports[awesome()];
```

test.js:
```
var awesome = require('./main').awesome;
```

Then we're unable to extract named exports from main.js, but it's obvious there's "awesome" named export by analysing test.js. This could be automated to create database you mention.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
