### ISSUE TITLE
Handle files started with hashbang

### ISSUE THREAD

**Issue by FLamparski** [rollup/rollup-plugin-commonjs#126]
Basically identical issue to https://github.com/substack/node-browserify/issues/297.

Some node files may try to be clever and be both a module you can import _and_ their own CLI, and node allows this by ignoring the hashbang. Example:

> ifmain.js:
> 
> ``` js
> #!/usr/bin/env nodejs
> if (require.main === module) {
>   console.log('main');
> } else {
>   module.exports = 'not-main';
> }
> ```
> 
> Shell:
> 
> ``` sh
> $ ./ifmain.js
> main
> ```
> 
> REPL:
> 
> ``` sh
> $ node
> > require('./ifmain')
> 'not-main'
> ```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
