### ISSUE TITLE
Generates empty object.freeze() vars

### ISSUE THREAD

**Issue by giantbits** [rollup/rollup-plugin-commonjs#142]
Hi

I'm not sure I'm blaming the right source of my problem. I'm trying to get "qwest" to work with rollup. Qwest has dependencies to pinkyswear and jquery-param. During build process jquery-param get's treated nice and well but with pinkyswear some stranger things are happening that I don't understand.

The main problem is, that it always ends with something along the lines of:

`var pinkyswear = Object.freeze({

});`

The final result is a "pinkyswear is not defined" within the browser. I made a small demo repo, so you can have a look at it: [qwest-test](https://github.com/giantbits/qwest-test).

Has this indeed something to do with rollup-plugin-commonjs or is this the result of something completely different?

Thanks for clearing this up.

Steffen

**Comment by Rich-Harris** [comment]
I got a slightly different error – possibly caused by different versions of plugins, etc – but the nub of the issue was that the `globals` plugin was preventing the `commonjs` plugin from working by adding an `import` declaration. If you swap the plugin order such that `globals` runs *after* `commonjs`, it seems to work okay.

Raised a related issue this morning: https://github.com/rollup/rollup/issues/1148

**Comment by giantbits** [comment]
Really? I changed the order while trying to fix the problem but missed your suggested order. Thank you very much!
