### ISSUE TITLE
Output requires module which isn't in the dependency chain

### ISSUE THREAD

**Issue by viveleroi** [rollup/rollup-plugin-commonjs#145]
I have the [uuid module](https://www.npmjs.com/package/uuid) as a dependency, and I have `browser: true` in the nodeResolve plugin config. I can't tell 100% where this issue originates but in looking at the rollup-node-resolve code, it doesn't deal with anything but resolving files.

The uuid module has a `uuid.js` main file, which has `require('./lib/rng')`.

However, there are two different lib files, one which gets loaded in the browser:

`"browser": {"./lib/rng.js": "./lib/rng-browser.js"}`

With rollup, my umd output somehow has `require('crypto'))`despite having included the `rng-browser.js` code. Since I'm using requirejs and crypto wasn't a module, I get:

`require.min.js:1 Uncaught Error: Script error for "crypto"`

The only reference to `require('crypto')` in the source files is the original `./lib/rng.js` which was replaced, so I'm confused where the name `crypto` is coming from.

I do see `Treating 'crypto' as external dependency` during the build process, but uuid is the only module I use that references crypto - which I confirmed by building a file with *only* `import uuid from 'uuid';`. I've tried setting up exclude rules for that file but it just winds up including *both* rng lib files.

**Comment by Rich-Harris** [comment]
Please see https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

**Comment by viveleroi** [comment]
https://github.com/viveleroi/rollup-uuid-require-bug

**Comment by Rich-Harris** [comment]
Thanks, I understand the problem now. The issue here is that – due to some spectacularly unfortunate design decisions taken in the early days of Node – the `commonjs` plugin has to resolve  module IDs by itself, to account for `foo` meaning `foo/index.js` and other such nonsense. But it's not equipped to handle things like `pkg.browser`, because that's the job of `node-resolve`.

The solution is actually very straightforward – you just need to ensure that the `node-resolve` plugin runs before the `commonjs` plugin. The real question I'm wondering about is how to make that more obvious, because it requires quite a deep understanding of the order in which various plugin operations take place.

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/rollup/rollup/issues/1148

**Comment by viveleroi** [comment]
Thanks, that solved the error. Until there's a fix to rollup it would be helpful to document this, or make it more prominent if it is and I just missed it.
