### ISSUE TITLE
import may only appear at top level in conjunction with rollup-plugin-babel

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-commonjs#146]
Via https://github.com/rollup/rollup-plugin-babel/issues/58. The issue is that the Babel plugin adds

```js
import * as babelHelpers from 'babelHelpers';
```

to a CommonJS module that contains ES2015 code, which might then get wrapped in a function block by this plugin. The end result is an `import` declaration that's not at the top level, which Rollup then fails to parse.

The workaround is straightforward – ensure the `commonjs` plugin runs before the `babel` plugin. But it'd be nice if this confusion could be avoided altogether, perhaps by hoisting `import` declarations.

**Comment by bfred-it** [comment]
Related https://github.com/rollup/rollup/issues/1148

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
