### ISSUE TITLE
Should dedupe namedExports

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-commonjs#148]
While investigating https://github.com/rollup/rollup-plugin-commonjs/issues/137, I found that `namedExports` can duplicate automatically inferred exports.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
