### ISSUE TITLE
skipping exports in entry module produces error

### ISSUE THREAD

**Issue by simomat** [rollup/rollup-plugin-commonjs#188]
When rollup-plugin-commonjs is used and rollup is configured to skip generate exports ([see https://github.com/rollup/rollup/wiki/JavaScript-API#exports](https://github.com/rollup/rollup/wiki/JavaScript-API#exports)) like that:
```javascript
export default {
    entry: './src/app.js',
    plugins: [ require('rollup-plugin-commonjs')() ],
    exports: 'none'
};
```
, an error is produced:
> 'none' was specified for options.exports, but entry module has following exports: default

edit: even if the entry module does not export anything.

**Comment by bfred-it** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by nerdbeere** [comment]
Hey there,

I currently experience the same issue and created a simple repro: https://github.com/nerdbeere/rollup-export-none-test-case

Let me know if you need any further help reproducing it.

**Comment by git-jiby-me** [comment]
@bfred-it any way to work around this ?

**Comment by jamesseanwright** [comment]
Still seeing the same issue. More than happy to investigate when I have some free time next week.

**Comment by jamesseanwright** [comment]
I was able to resolve this issue [within my fork of this repo](https://github.com/rollup/rollup-plugin-commonjs/compare/master...jamesseanwright:master). However, I need to update some of the tests, and there a few idiosyncrasies that I don't understand, namely the [`__moduleExports` computed export](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/index.js#L189). Please could someone explain why this exists and how it is used by the plugin?

Cheers!

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
