### ISSUE TITLE
RxJS modular method adding doesn't work

### ISSUE THREAD

**Issue by slikts** [rollup/rollup-plugin-commonjs#190]
RxJS issue: https://github.com/ReactiveX/rxjs/issues/2554

Simplified repro: https://github.com/slikts/rxjs-rollup-example/tree/simplified

**Comment by clavery63** [comment]
Is this still an issue?  The following works for me

```javascript
import displayText from './displayText';
import { Observable } from 'rxjs/Observable.js';
import 'rxjs/add/observable/interval';

const displayInterval$ = Observable.interval(1000);

displayInterval$.subscribe(num => displayText(`My favorite number is ${num}`));
```

**Comment by Shyam-Chen** [comment]
```js
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/interval';

Observable.interval(1000)
  .subscribe(value => console.log(value));
```

```bash
commonjs-proxy: node_modules/rxjs/util/root.js (1:135) 'default' is not exported by 'node_modules/rxjs/util/root.js'
```

**Comment by Shyam-Chen** [comment]
```js
// error
import globals from 'rollup-plugin-node-globals';
import builtins from 'rollup-plugin-node-builtins';
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
