### ISSUE TITLE
Reading `require` keyword when used inside of a comment

### ISSUE THREAD

**Issue by ajhyndman** [rollup/rollup-plugin-commonjs#199]
I can try to isolate this later, but I have a diff in my project wherein my rollup build dies because of an attempt to import `undefined`.  After some serious head-scratching, I finally realized that the require keyword had been resolved inside of a **comment**, and then interpreted as an import statement with no target!

This seems like a bug.  😄 

Failing diff;

https://github.com/ajhyndman/fire-emblem-working-title/commit/4e0b8fa029e8557b3d6d16e5bae99e6e7532e0ac

CI failure:

https://circleci.com/gh/ajhyndman/fire-emblem-working-title/145?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
