### ISSUE TITLE
"Duplicate export 'default'" when only module.exports.default is defined

### ISSUE THREAD

**Issue by AndrewKvalheim** [rollup/rollup-plugin-commonjs#209]
Not very familiar with JS tooling so apologies if this is obvious. I think I'm still seeing a variant of #158.

Test case:

```javascript
// test/function/duplicate-default-exports-only-default/x.js

module.exports.default = 42;
```

```javascript
// test/function/duplicate-default-exports-only-default/main.js

import x from './x';
```

```console
$ yarn test
[...]
  61 passing (537ms)
  1 failing

  1) rollup-plugin-commonjs function duplicate-default-exports-only-default:
     Error: Duplicate export 'default'
      at error (node_modules/rollup/src/utils/error.js:2:14)
      at Module.error$1 [as error] (node_modules/rollup/src/Module.js:303:2)
      at tryParse (node_modules/rollup/src/Module.js:27:10)
      at new Module (node_modules/rollup/src/Module.js:53:15)
      at node_modules/rollup/src/Bundle.js:301:20
      at <anonymous>
[...]
```

In the wild: [cheerio 1.0.0-rc.2 at `lib/options.js`](https://github.com/cheeriojs/cheerio/blob/1.0.0-rc.2/lib/options.js#L7)

**Comment by bjrnt** [comment]
I'm having this issue as well. Did you find any solution?

**Comment by AndrewKvalheim** [comment]
No, I didn't pursue this any further; just opted not to use Rollup for this project.

**Comment by futurist** [comment]
Any update for this? that is very common error when using rollup, with this issue, and cannot be resolved?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
