### ISSUE TITLE
Is "named exports" feature or bug?

### ISSUE THREAD

**Issue by Firanolfind** [rollup/rollup-plugin-commonjs#211]
Lately I tried to switch from **browserfy** to **rollup** (treeshaking attracted me), but I faced with wall of problems. It looks strange that to start default bundler working behavior I have to add some plugins (one `rollup-plugin-node-resolve`, two `rollup-plugin-commonjs`).
But most frustrating I got trying to start it working with **React**. I spend hours of my life trying to solve **[EXTERNAL DEPENDENCY RESOLVING](https://github.com/rollup/rollup-plugin-commonjs/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20Dependency%20)**, and I found out that one have to list all modules manually and even export names _(sic!)_ like:
```javascript
CommonJs({
	include: 'node_modules/**',
	namedExports: {
		'./node_modules/react/react.js': 
		['cloneElement', 'createElement', 'PropTypes', 'Children', 'Component'],
	}
}),
```
**Is it feature or bug?** Am I doing something wrong or this tool is just ~~sucks~~crude? I appreciate your hard work guys, but after loosing so much time, I feel disappointed.

BTW It takes 13 second to build empty project. No uglify.
![jpeg image 568 x 335 pixels](https://user-images.githubusercontent.com/4816603/28667398-045f36d6-72d4-11e7-9de8-31647a2a9851.png)

![jpeg image 568 x 335 pixels](https://user-images.githubusercontent.com/4816603/28667032-65f46152-72d2-11e7-8c66-9366d09433e2.jpg)

**Comment by vianvio** [comment]
same issue for me, if anyone knows the right way to do this(I mean make things work, and no need to list all functions, just like webpack does), please help. It's already token me one day for researching how to make a hello world with rollup and react...

**Comment by vianvio** [comment]
haha...can't believe that I found the right way just few minutes after I posted up there...
It is answered by @olsonpm in #201 , just change the order of the plugins.
Here is my new order of plugins
` plugins: [
    resolve({
      jsnext: true,
      main: true,
      browser: true
    }),
    commonjs({
      include: 'node_modules/**'
    }),
    nodeGlobal(),
    babel({
      exclude: 'node_modules/**',
    })
  ]`

And I write the hello world in this way
`import React from 'react'
import ReactDom from 'react-dom';

class App extends React.Component {
  constructor() {
    super();
    this.state = {};
  }
  render() {
    return <div>Hello</div>;
  }
}

ReactDom.render(<App />, document.getElementById('root'));`

It's working !!!! Hope this will help you too.

**Comment by Rich-Harris** [comment]
Closing as there's a solution in the comments, and the rationale for `namedExports` is [clearly explained](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) in the README. Webpack gets around the need for `namedExports` by keeping everything as CommonJS modules and implementing Node's `require` system in the browser, which is why the resulting bundles are larger and take longer to start up. Both options are valid, but that's the tradeoff to be aware of — more config (Rollup, when using modules like React), or larger bundles (webpack).

**Comment by ayqy** [comment]
Cool solution, happy to find this after several hours, DO NOT want to bow to the SLOW webpack.

This issue is really annoying, and I resolved it one project to another last year, maybe we should *document the specific order of plugins need*, or where can we find existing tips I missed? @Rich-Harris 

After all, a clean & fast bundle is what we definitely need, and it's almost the killer feature of rollup I think. However, building bundles with webpack just like jogging on the playground, and rolluping it seems to a real war.

**Comment by thomasgwatson** [comment]
Blrugh, I've followed the warnings and documentation about how to deal with dependencies like React and it continues to plague me (perhaps because I am using Lerna and it does weird things with node_modules).

`import babel from 'rollup-plugin-babel'
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'

export default {
  input: 'src/index.js',
  plugins: [
    commonjs({
      include: 'node_modules/**',
      namedExports:
      {
        '../../node_modules/react/index.js:
        [
           'React',
           'cloneElement',
           'createElement',
           'PropTypes',
           'Children',
           'Component',
        ],
      }
    }),
    resolve(),
    babel({
      exclude: 'node_modules/**'
    }),
  ],
  output: {
    name: "Button",
    format: process.env.format,
    file: `../../dist/Button/index.${process.env.format}.js`
  }
}`

even with all that, I still get `[!] Error: 'default' is not exported by ../../node_modules/react/index.js`

I've tried changing the path reference to React, I've juggled the order of the plugins. No dice.

**Comment by thomasgwatson** [comment]
This seems to be best option we got at the moment: just don't include problematic externals and list them as peerDependencies:

https://github.com/transitive-bullshit/react-modern-library-boilerplate
