### ISSUE TITLE
Suggestion: No longer add named exports for CJS modules

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup-plugin-commonjs#228]
This is a continuation of a discussion started in rollup/rollup#1637. The main point is: 

Now that node natively supports ES6 modules, should rollup's implementation of CJS imports be changed to match [node's implementation](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#46-es-consuming-commonjs)? I.e., only provide a default export for CJS modules?

**Advantages**
* Compatibility with node, obviously
* More consistent behaviour in some corner cases

**Disadvantages**
* Breaking change for many users
* Incompatibility with Webpack which seems to follow [this spec](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies)

Personally I think that going the node way would be preferable as we will have less problems with inconsistencies and compatibility with a spec that has taken a long time to mature. But if we implement this change, it needs to happen in a way that
* Educates the users with warnings what will be happening and why they should change their code
* Has a reasonably long switch-over period that also allows for ES6 library maintainers to adapt their code in case this should be necessary
* Possibly provides a new option that people can set to retain the old behaviour

Of course, more input on this topic is always welcome.

**Comment by kzc** [comment]
-1 

I see no practical advantages in this proposal - only breakage.

**Comment by jacksonrayhamilton** [comment]
Achieving compatibility with Node is a practical benefit and a compelling argument for doing this.

However, I'll go a little deeper, and claim this change is rooted in exposing the fallacy that properties of the CommonJS `exports` object map to exports of ECMAScript modules.  Both the generation and consumption of CJS → ES would be more elegant if we eliminated this fallacy and its inevitable consequence.

For the fallacy, here is a proof by contradiction:

1. It is desirable that the whole CJS `exports` object be consumable, since entire APIs are often made exclusively available via `exports` (e.g. by assigning a value to `module.exports`).  So, we will transform `exports` into the "default" ES export.  `module.exports = {}` can be consumed like `import foo from 'foo'` (commonly), or like `import {default as foo} from 'foo'` (formally).
1. It seems desirable that the properties of the CJS `exports` object also be made importable, where the names used to import properties' values correspond to those properties' values' respective keys.  We want to consume `exports.bar = {}` like `import {bar} from 'foo'`.
1. In CJS, in addition to assigning a value to `module.exports`, it is also possible to assign a property named "default" to `exports`; e.g., `exports.default = {}`.
1. `module.exports` and `exports.default` cannot both be the export named "default".  It is a contradiction that A equals not-A.

The matter of which value *should* be the export named "default" is arbitrary.  `module.exports` would be nearly universally more practical than `exports.default`, but by the logic of mapping export names to object properties, `exports.default` remains a perfectly legitimate conclusion.

It possible to introduce a special exception into the mapping, where all names map to properties' values' respective keys, *expect for the name "default"*.  However, this exception was logically *unnecessary!*  The result is a mapping which forfeited an ideal consistency and simplicity.  I would regret passing on those values when they were within my reach.

One may achieve the practicality of consuming `exports` *and* enjoy an ideally consistent and simple mapping by alleviating himself of the desire to import properties of `exports` by name.  i.e., rather than `import {bar} from 'foo'`, do `import foo from 'bar'` and `foo.bar`.

**Comment by jacksonrayhamilton** [comment]
While breakage is unfortunate, it's also something to have been anticipated.  Previous attempts to make CJS and ES interoperate involved predictions about named exports.  Those predictions will (most likely) be wrong.

For Webpack compatibility, Webpack should also implement this issue's suggestion.  I believe the logic is just as true for this tool as for that one.  Ideally, the tools can make this change in unison to avoid cultural dissonance on compilation strategies.

Another advantage of this suggestion is that the implementation of "CJS → ES" compilation will be simpler.  The algorithm for transforming `exports` properties into named exports [is complicated](https://github.com/rollup/rollup/issues/1637#issuecomment-330148100) due to the special exceptions it defines.  Those exceptions aren't even strictly necessary for accessing the exported values.

Another advantage is that the consumption of CJS `exports` properties can be simpler.  Library authors only providing a CJS module will not also provide named exports necessarily.  That is, instructing the use of a module is minimally and comprehensively accomplished like this:

> To do X, call the `bar()` procedure:
>
> ```js
> var foo = require('foo'); // CJS
> import foo from 'foo'; // ES
> foo.bar();
> ```

Currently, Rollup is generating its own flavor of API:

> CommonJS API:
>
> ```js
> var foo = require('foo');
> foo.bar();
> ```
>
> Rollup- and Webpack-flavored ES API:
>
> ```js
> import {bar} from 'foo';
> bar();
> ```
>
> Node ES API:
>
> ```js
> import foo from 'foo';
> foo.bar();
> ```

Leave it to the library author to decide if they want there to be multiple ways for people to use their API.  Personally, I'd rather the API be as simple as possible.  (Not conditionally environment-"enhanced!")

Additionally, in the latter example of module consumption strategies, the "Rollup- and Webpack-flavored ES API" is typically documented as "ES6," and a distinct "Node" ES example is not included.  The introduction of Node's ES implementation is going to increase the complexity of the API space in which Rollup will cause (more) dissonance.

**Comment by kzc** [comment]
> Achieving compatibility with Node is a practical benefit and a compelling argument for doing this.

Node is proposing to implement a subset of the ES module spec for commonjs interoperability. The latest versions of `rollup` and `rollup-plugin-commonjs` already support that subset. All the CJS import examples from the Node ES module draft work as is in Rollup:

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#4611-examples

As for named imports of CJS modules not being supported by Node, that's fine. Rollup users can elect not to use named import syntax if they want. There's no reason to break existing projects that happen to use that functionality.

**Comment by jacksonrayhamilton** [comment]
> There's no reason to break existing projects that happen to use that functionality.

Existing projects using that functionality will already be broken, should anyone try to consume those projects in Node natively.  One reason to break projects is to stop validating an anti-pattern, or rather, a non-pattern.

More on "unintended APIs," from my last comment... [the referenced specification](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies) section on named exports bothers me:

> For convenience, named exports are also auto-populated but may not be correctly bound as expected, so use these carefully.

Pointing out the potential danger of unbinding methods doesn't excuse its practice.  It's not the responsibility of a consumer to know what module system an API was created in, such that they might deduce whether this named export API which some tool generated is potentially unsafe to use.  Essentially, this spec counts on everyone in the tool author / tool blog post writer / tool user / library author sphere to be aware of this potential danger, which could have been easily eliminated by eliminating the unnecessary feature, itself.

For an idea of what type of code is made available in a broken state when it's automatically exported, take for instance this beginning of a `Promise` polyfill:

```js
class Promise {}
exports = module.exports = Promise;
exports.all = function () {
  return new this(function () {});
};
```

```js
import Promise, {all} from 'promise';
Promise.all(); // Returns a Promise
class ExtendingPromise extends Promise {}
ExtendingPromise.all() instanceof ExtendingPromise; // Returns true
all(); // Throws "Uncaught TypeError: this is not a constructor"
```

**Comment by kzc** [comment]
> Existing projects using that functionality will already be broken, should anyone try to consume those projects in Node natively.

But most Rollup users are targeting the browser, and for them it doesn't matter. And for the minority of server side cases that elect to port to Node, once they do it could run in Rollup as is. Rollup supporting a superset of what Node supports is not an issue.

As for npm packages changing over from CJS to ES modules, their respective APIs would change anyway in most cases so consumers of that code would have to change their programs accordingly - when or if each particular module changes. But luckily npm packages are versioned so no urgency there. Users can upgrade each package at their convenience.

**Comment by jacksonrayhamilton** [comment]
> And for the minority of server side cases that elect to port to Node, once they do it could run in Rollup as is. Rollup supporting a superset of what Node supports is not an issue.

The dream of ES modules is that someday they'll be able to interoperate across platforms natively.  The line of thinking that we can extend the language on a whim dooms us to eternal dependency on a build tool.

**Comment by kzc** [comment]
A practical point to consider - commonjs named imports are tree shaken by Rollup and module imports are not. As result named imports will produce smaller code than module imports with latest `rollup` + `rollup-plugin-commonjs` + `uglify-es`:

Given:
```
$ cat exports.js 
exports.foo = 1;
exports.bar = 2;
exports.square = function square(x) { return x * x; };
exports.cube = function cube(x) { return x * x * x; };
```
Named commonjs imports:
```
$ cat import_named.js 
import { foo, cube } from './exports.js';
console.log(foo, cube(3));
```
```
$ cat rollup.named.js 
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

export default {
  input: 'import_named.js',
  output: {
    file: 'import_named.out.js',
    format: 'es',
  },
  plugins: [
    commonjs(),
    uglify({
        toplevel: true,
        compress: {
          passes: 3,
          pure_getters: true,
          unsafe: true,
        },
    }, minify),
  ]
};
```
```
$ bin/rollup -c rollup.named.js --silent && cat import_named.out.js
console.log(1,27);
```
Import by module name:
```
$ cat import_module.js 
import Mod from './exports.js';
console.log(Mod.foo, Mod.cube(3));
```
```
$ cat rollup.module.js 
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

export default {
  input: 'import_module.js',
  output: {
    file: 'import_module.out.js',
    format: 'es',
  },
  plugins: [
    commonjs(),
    uglify({
        toplevel: true,
        compress: {
          passes: 3,
          pure_getters: true,
          unsafe: true,
        },
    }, minify),
  ]
};
```
```
$ bin/rollup -c rollup.module.js --silent && cat import_module.out.js
var o={foo:1,bar:2,square:function(o){return o*o},cube:function(o){return o*o*o}};console.log(o.foo,o.cube(3));
```
Worth noting that Google Closure can reduce `import_module.out.js` to match the smaller result in `import_named.out.js` above.

**Comment by Rich-Harris** [comment]
I think the tree-shaking consideration probably outweighs all others for the time being, at least until Rollup is smart enough to remove unused properties the same way Closure does.

Past that point, I definitely *do* see the appeal of removing named imports, if only because it would eliminate a lot of confusion (no more needing to explain `namedExports` — we just say 'if you're importing CommonJS, use the default export', which people will have been trained to do by Node anyway). The fact that it would greatly simplify this plugin (and eliminate the weird edge cases noted above) is a nice bonus.

**Comment by jacksonrayhamilton** [comment]
@kzc  Regarding this:

> As for npm packages changing over from CJS to ES modules, their respective APIs would change anyway in most cases so consumers of that code would have to change their programs accordingly - when or if each particular module changes.

Rollup should not be responsible for predicting and generating APIs.  It's not necessary to fulfill Rollup's stated purpose of "compiling small pieces of code into something larger and more complex."

Designing APIs is an author's responsibility.  You assume that they will change to look a certain way, but this is not necessarily true.

Consumers of code should only start to access that code via an ES module API once that code is actually an ES module.  As I've demonstrated, it's risky to behave like `exports` is something other than an object and the lone and default export.

@Rich-Harris  Rollup should not be responsible for reducing bytes.  Minifiers already do that.

It seems reasonable enough that, when bundling many ES modules into one ES module, Rollup could assemble all imported values, and all the values which those imported values needed from their respective scopes, into one file.  This could just as easily be perceived as "dead code removal" as "a nice side effect of only including what's used."

But this implementation detail isn't even particularly useful.  Whether "all code" or "only the used ES exports" were included, the bundle would still be larger than a minified bundle.  And, a minifier with dead code elimination would produce a bundle of the same size from either input.  It doesn't make sense to argue from the standpoint of optimization.

Features should only be added to Rollup if they permit JavaScript to be bundled.  Eliminating the unused properties of an `exports` object isn't necessary for using CommonJS code within other code.  They were only coincidentally eliminated before because they were first transformed into ES exports.  I believe I've proven that transformation to be logically-incorrect or complex, and error-prone.

The way forward is to accept that creative liberties and optimizations shouldn't be a goal of the project.  Instead, simplicity and correctness should be goals.

**Comment by lukastaegert** [comment]
Adding to this, I think there is a good chance Rollup's tree-shaking algorithm will eventually catch up to be able to do proper tree-shaking even without the translation to named exports. The more important question in my opinion is if and how such a transformation could take place in a way that is as painless for our users as possible. This is how it might be achieved:
1. We add a new flag to rollup-plugin-commonjs, e.g. `extractNamedExports`. The default value for this flag should be true so that it is not a breaking change.
2. If this flag is not specified explicitly, we print a warning that we are extracting named exports for now but that this behaviour will change in the future unless the user explicitly sets this flag to true. We also include a link to a wiki page outlining the reasoning and why they should set this flag to false if their dependencies permit it. This is the most important part where we educate users. It is important especially to communicate to library developers that they might need to change their code.
3. We write this wiki page :)
4. To ease the transition, we make sure the following is true in Rollup:
    * If a named export is used but only a default export is present, we tell the user that this is the case and that this might be due to (link to Wiki page). On the wiki page or in the error, we tell them that they probably want to use something like `import lib from './lib.js'; const named = lib.named`
   * If a default export is used but only named exports are present, we also tell the user so and as a convenience should actually list all named exports. We tell them that they can probably write `import * as lib from './lib.js'`. This is important for the case when a library switches from CJS to ES6 modules as this transition will also become more painful for the user and information is important.
5. We possibly extend the `extractNamedExports` option to also accept a list of imports that should use the old behaviour. That way, stubborn libraries can be tamed individually without breaking the default.
6. We switch the default behaviour to not include named exports :)
7. We hope that the likes of Webpack follow our lead.

What do you think, did I miss anything important? Still, quite a long laundry list.

**Comment by jacksonrayhamilton** [comment]
> Adding to this, I think there is a good chance Rollup's tree-shaking algorithm will eventually catch up to be able to do proper tree-shaking even without the translation to named exports.

I am suggesting that optimizations to code stop being a concern for Rollup.  I don't think we should be talking about tree-shaking unless we can justify it.

Regarding this plan...

I think this feature should be completely removed from Rollup.  By realizing that "`exports` object → `export default` only" is the correct behavior, we are also realizing that user's code was supposed to have been broken.  They were led to believe that they could do something that they shouldn't have been able to do.  Everyone was wrong, and everyone should undo the damage.

Apparently people want to do this and existing code does this:

foo.js:

```js
module.exports = {a: 1, b: 2}
```

Another file:

```js
import {a, b} from './foo.js'
```

If people must indulge themselves or others in this fantasy, rather than legitimize it as a feature in Rollup, there should be a Babel plugin that transforms their code into:

```js
import foo from './foo.js'
const {a, b} = foo
```

A Babel plugin can solve the problem of backwards compatibility with broken code.  The act of installing a plugin will make apparent to users that what they are doing is extraordinary, and encourage everyone to fix their code so that the plugin won't be necessary.

The Babel plugin could also be utilized in an "upgrading" utility which recurses files in a repository, permanently fixing them all to access `exports` properties correctly.

Regarding messaging as part of the plan:  I agree that we should highlight code that used to compile and now won't.  We should suggest the alternative correct form, i.e. accessing properties of a JavaScript object.  Using emotional language such as "If you don't like that...", we can offer the Babel plugin as an alternative.

Regarding this:

> If a default export is used but only named exports are present...

It will never be the case that "only named exports are present."  Doing "`exports` object → `export default` only" means that only a default export will ever be present.

Regarding this:

> We hope that the likes of Webpack follow our lead.

We should not just hope, but implore that Webpack's maintainers do the same.  Although, Webpack's scope and willingness for complexity seems to be broader, so convincing them might be harder.

**Comment by lukastaegert** [comment]
I like the idea of a plugin to handle that. This would really make it much cleaner. My main concern is that important libraries depend on Rollup's bundling process and even if they do everything right, they cannot be sure that all their dependencies do the same. So for these users, there needs to be a clear path to follow.
A babel plugin + clear documentation on when and how to add it could just be that path–and we could immediately get rid of quite a bit of convoluted code.

> I am suggesting that optimizations to code stop being a concern for Rollup. I don't think we should be talking about tree-shaking unless we can justify it.

I beg to disagree a little on this point. Of course I am very biased here as a lot of my time is currently spent towards further improving the tree-shaking algorithm. Two points here:
* Rollup's tree-shaking is superior to what most minifiers (besides possibly Closure Compiler) can currently do as it directly uses all advantages the ES6 module system grants it. To achieve that, it also makes use of the fact that tree-shaking is integrated with the bundling process.
* Tree-shaking is one of the two most important "marketing features" of rollup, the other one being scope-hoisting. I think this is one of the reasons why libraries such as React or Moment chose to adopt it in the first place.

That said, just like you I favour correctness of possible gains that hinge on mere heuristics. My goal for all future improvements to the algorithm is to only eliminate code if we are utterly sure we can do so safely.

As I side note, one of my mid-term goals is to make the tree-shaking algorithm a modular component of rollup so that other libraries, even Webpack, can make use of it. At that point, we may start to re-think how everything should play together.

**Comment by kzc** [comment]
Be aware that commonjs module imports + Closure only match the size of commonjs named imports + Closure in Advanced optimization mode, which can break code if [Closure's restrictions](https://developers.google.com/closure/compiler/docs/limitations#restrictions-for-advanced_optimizations) are not followed. Dropping unused properties is a difficult problem due to the dynamic nature of javascript. A future version of Rollup may be able to make some assumptions about properties in the `import` module case to produce equivalent code.

Even if the two import schemes produced the same sized bundles, I don't understand the desire to drop the widely used and useful commonjs named imports, especially since the code already exists and it's an optional feature harming no one. Removing features from software is never well received.

**Comment by lukastaegert** [comment]
Btw. #159 is a direct result of the rollup's futile attempt at detecting named exports. Basically, named export detection cannot work properly in any situation where these exports are added dynamically inside e.g. IIFEs etc.
Maybe another approach is to actually create two plugins - a rollup-plugin-commonjs and a rollup-plugin-commonjs-legacy (or rollup-plugin-commonjs-named-exports) where only the latter adds named exports?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
