### ISSUE TITLE
Circular dependencies break at build time: '__moduleExports is not exported'

### ISSUE THREAD

**Issue by arcanis** [rollup/rollup-plugin-commonjs#234]
Minimal showcase: https://github.com/arcanis/rollup-circular-commonjs, running `yarn && yarn rollup -c` should be enough to reproduce the issue.

The gist is that given two commonjs files that refer to each other, the build will fail with the following error:

```
a → bundle.js...
[!] Error: '__moduleExports' is not exported by a.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/mael/rollup-error/a.js (1:9)
1: import { __moduleExports } from "/Users/mael/rollup-error/a.js"; export default __moduleExports;
```

This doesn't happen with es6 modules.

**Comment by LizzyBradley** [comment]
Any progress? I am also running into this issue.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
