### ISSUE TITLE
Apparently incorrect ECMAScript 2015 imports from acorn and resolve

### ISSUE THREAD

**Issue by haraldrudell** [rollup/rollup-plugin-commonjs#236]
Confusion around default and named exports

If used with rollup, errors prevent successful build

Pull request coming up…

```[!] Error: 'default' is not exported by node_modules/acorn/dist/acorn.es.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.es.js (5:7)
3: import { sync } from 'resolve';
4: import { attachScopes, createFilter, makeLegalIdentifier } from 'rollup-pluginutils';
5: import acorn from 'acorn';
          ^
6: import { walk } from 'estree-walker';
7: import MagicString from 'magic-string';

[!] Error: 'default' is not exported by node_modules/acorn/dist/acorn.es.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.es.js (5:7)
3: import { sync } from 'resolve';
4: import { attachScopes, createFilter, makeLegalIdentifier } from 'rollup-pluginutils';
5: import acorn from 'acorn';
          ^
6: import { walk } from 'estree-walker';
7: import MagicString from 'magic-string';
```

**Comment by haraldrudell** [comment]
Node.js v8.4.0
rollup-plugin-commonjs@8.2.1
rollup@0.50.0

It is unclear to me in what environment those imports could ever have worked.
It seems acorn never had a default export
Because Rollup uses the plugin internally, Rollup may fail even if the rollup.config.js does not import the plugin

**Comment by Rich-Harris** [comment]
Can you describe the situation in which this is failing in more detail? `acorn` is never bundled into this plugin, so it normally wouldn't matter whether you do `import acorn` or `import { parse }` (the first is just a hangover from older versions of acorn), because Rollup takes care of CommonJS interop. It probably *should* be `import { parse }`, but I'd like to understand the problem before changing anything, lest it cause issues for other people.

**Comment by haraldrudell** [comment]
Comment is here: https://github.com/rollup/rollup-plugin-commonjs/pull/237#issuecomment-334970620
