### ISSUE TITLE
Support for "this" exports in CommonJS modules

### ISSUE THREAD

**Issue by jjordan-dff** [rollup/rollup-plugin-commonjs#254]
I've ran into an issue trying to import the [circular-json](https://github.com/WebReflection/circular-json) node module in a rollup bundle. The module's exports are missing because it uses "this" as a shorthand for "module.exports" (as can be seen in the terminal output below). Is it possible to add support for this syntax to rollup-plugin-commonjs?

Here is my rollup config:
```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
    input: 'index.js',
    output: {
        file: 'app.bundle.js',
        format: 'iife'
    },
    plugins: [
        resolve(),
        commonjs()
    ]
};
```
And this is the index.js:
```
import * as cj from "circular-json";

cj.stringify({});
```
Rollup output:
```
index.js → app.bundle.js...
(!) `this` has been rewritten to `undefined`
https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
node_modules\circular-json\build\circular-json.node.js
182:   return JSON.parse(text, generateReviver(reviver));
183: }
184: this.stringify = stringifyRecursion;
     ^
185: this.parse = parseRecursion;
...and 1 other occurrence
(!) Missing exports
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
index.js
stringify is not exported by node_modules\circular-json\build\circular-json.node.js
1: import * as cj from "circular-json";
2: 
3: cj.stringify({});
      ^
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
