### ISSUE TITLE
Can't handle shebang

### ISSUE THREAD

**Issue by mnpenner** [rollup/rollup-plugin-commonjs#261]
I'm not sure what parser this plugin uses but it seems to choke on a lot of different things. In particular, it's dying on this shebang:

```
Unexpected character '#' (1:0) in /home/me/Projects/myproj/src/index.js
> 1 | #!/usr/bin/env node
    | ^
  2 | 
  3 | const Path = require('path');
  4 | const Json5 = require('json5');
{ SyntaxError: Unexpected character '#' (1:0) in /home/me/Projects/myproj/src/index.js
    at error (/home/me/Projects/myproj/node_modules/rollup/dist/rollup.js:189:14)
    at Promise.resolve.then.catch.err (/home/me/Projects/myproj/node_modules/rollup/dist/rollup.js:17590:6)
    at <anonymous>
  pos: 0,
  loc: Position { line: 1, column: 0 },
  raisedAt: 0,
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  id: '/home/me/Projects/myproj/src/index.js' }
```

I'm not sure whether or not there's a Babel transform to strip shebangs but I shouldn't have to -- I really do want that in the output.

Node obviously runs this just fine so it shouldn't be a syntax error.

**Comment by adrianheine** [comment]
`acorn` has an option called `allowHashBang`, that would solve this issue.

**Comment by davidenke** [comment]
For the time being I helped myself with a little plugin function:
```js
const removeShebang = (options = {}) => ({
  name: 'rollup-plugin-remove-shebang',
  transform: (code, id) => {
    const includes = options.include || ['node_modules'];
    if (includes.some(include => id.includes(include))) {
      return code.replace(/[\s\n]*#!.*[\s\n]*/, '');
    }
    return null;
  }
});
```

Usage example:
```js 
export default {
  plugins: [
    removeShebang({ include: ['node_modules/ecstatic/lib/ecstatic.js'] })
  ]
};
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
