### ISSUE TITLE
> 8.0.2 breaks fs.stat / watching

### ISSUE THREAD

**Issue by brianmhunt** [rollup/rollup-plugin-commonjs#268]
The plugin seems to add `\u0000commonjsHelpers` to the list of watched files when using karma and rollup together.

Unfortunately `fs.stat` chokes on null byte via https://github.com/paulmillr/chokidar/blob/master/index.js#L632, when called from karma-rollup-preprocessor.

The behaviour began to exhibit after 8.0.2 i.e. rollup-plugin-commonjs worked as of version 8.0.2, but the failure exhibits now, with 8.2.6.

The central issue is the injection of a file with a null byte into the list of files rollup watches.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
