### ISSUE TITLE
include rxjs fail in angular4

### ISSUE THREAD

**Issue by hellheaven** [rollup/rollup-plugin-commonjs#269]
Hi there.
I used RXJS and ng2-file-upload in my project. I want to build production version in AOT.

Rollup failed when i include 2 modules like this:

> plugins: [
        nodeResolve({ jsnext: true, module: true, modulesOnly: false }),
        commonjs({
            include: ['node_modules/rxjs/**', 'node_modules/ng2-file-upload/**'],
namedExports: {
                 'node_modules/ng2-file-upload/index.js': ['FileUploader'],
                 'node_modules/rxjs/Subject.js': ['Subject']
            },
        }),
        uglify()
    ]

error info:
`Error: 'Subject' is not exported by node_modules\.5.5.6@rxjs\Subject.js`

and i change rollup-config like this:
` include: ['node_modules/**', 'node_modules/ng2-file-upload/**']`

RXJS just fine but FileUploader can not include.

`[!] Error: 'FileUploader' is not exported by node_modules\.1.3.0@ng2-file-upload\index.js`

How can i include then both?

**Comment by kumbiraibenjamin** [comment]
I currently have the same issue with this error, while thryin yo create umd file with rollup.js in Angular 4

[!] Error: 'Subject' is not exported by ../../node_modules/rxjs/Subject.js

Ive tried this but i still get an error.

       commonjs({
            include: 'node_modules/**',
            include: 'node_modules/rxjs/Subject.js',
            namedExports: {
                'node_modules/rxjs/Subject': [ 'Subject' ]
            }
        }

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
