### ISSUE TITLE
mixed import and require on same file deactivates plugin

### ISSUE THREAD

**Issue by zanona** [rollup/rollup-plugin-commonjs#273]
What's the expected output in the case where you have both ES6 import and Commonjs require in the same file? For example

```js
import foo from './foo'
const bar = require('./bar')

console.log(foo(), bar())
```

whenever I have ES6 `import` and Commonjs `require` in the same file, it seems the plugin simply ignores it altogether and doesn't import anything besides ES6 modules?

**Comment by znck** [comment]
Any update on this?

**Comment by adrianheine** [comment]
That's true, if a file includes `import` or `export` it's considered an ES module and not CommonJS, see https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L47.

**Comment by danielkalen** [comment]
@adrianheine any why is that considered ok?

**Comment by mgenware** [comment]
This bite me when working on a TypeScript project with rollup, I have to mix `require` and `import` to bypass the enforced type checking:

```ts
const styles = require('./styles/styles.css');
// the css file above will be converted to an ES module by another rollup plugin
// changing it to import causes resolve error and also confuses IDE
// now the require is ignored by rollup
import lib from './lib';

lib(styles);
```

Any ideas or solutions are appreciated 😃

**Comment by lukastaegert** [comment]
Unfortunately, mixing import and require is a "Webpackism" that is not supported by Rollup. Rollup only understands ESM, importing CommonJS (which uses `require`) is handled by rollup-plugin-commonjs which will skip this file due to the presence of the `import` statement.

Rollup is not able to completely replicate the semantics of `require` so I would seriously recommend to try to find a way to make `import` work.

**Comment by bterlson** [comment]
Closing this issue, but please feel free to re-open if you are unable to make import work.
