### ISSUE TITLE
Top level async

### ISSUE THREAD

**Issue by modulesio** [rollup/rollup-plugin-commonjs#281]
I realize this is a controversial one.

But if you require TL async you can't use this plugin at all, because top level sync is [baked in transform.js](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L360).

Any chance of optionalizing `async` here?

**Comment by Rich-Harris** [comment]
This is a CommonJS converter; CJS doesn't support top level `await` and never will, so neither should this plugin

**Comment by modulesio** [comment]
More details on the above: https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

I'm out of the loop, did a standards body make a declaration about CJS never having TLA?

**Comment by Rich-Harris** [comment]
I wrote that series of gists in response to a proposal to add top-level await to **ES modules**; I don't think anyone's ever suggested adding it to CommonJS because it doesn't really make sense — `require` is synchronous and that's never going to change.

**Comment by modulesio** [comment]
I'll definitely agree `require()` is sync and that ain't gonna change. It could theoretically await an async context at the source though, and therefore continue to return sync.

Actually, the only reason I need this is because of another (arguably badly designed) API I'm trying to emulate: `importScripts` of URL.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
