### ISSUE TITLE
Doesn't import file in correct order.

### ISSUE THREAD

**Issue by LvChengbin** [rollup/rollup-plugin-commonjs#284]
I don't know if this is an issue with this plugin or with `rollup`.

I required something in `core-js` with `import`, and code in `core-js` is this:

~~~js
// @@match logic
require('./_fix-re-wks')('match', 1, function (defined, MATCH, $match) {
  // 21.1.3.11 String.prototype.match(regexp)
  return [function match(regexp) {
      //...
  }, $match];
});
~~~

It requires a file './_fix-re-wks' which exports a `function`.

In the output file of `rollup`, the declaration of the function is later than calling it. So I got a `_fixReWks is not a function`.

There are also 4 or 5 others places that I need to rearrange the order of code and it is working well after I changed the order.

**Comment by adrianheine** [comment]
Could you provide a complete, reduced example reproducing the issue, maybe as a git repository?

**Comment by LvChengbin** [comment]
Thank you, and sure.

I have a project on Github https://github.com/LvChengbin/sequence.  
[sequence.bc.js](https://github.com/LvChengbin/sequence/blob/master/dist/sequence.bc.js) this is the file generated by `Rollup` with the config file [rollup.config.js](https://github.com/LvChengbin/sequence/blob/master/rollup.config.js).

For example, the function `_fixReWks` is called in `line 237`, but it is declared in `line 281`. So code from `line 262` to `line 307` should be moved to the line 114 after the declaration of `_global` and everything will be working well in browsers.

**Comment by LvChengbin** [comment]
sorry, I need to import something in `node_modules`.

**Comment by adrianheine** [comment]
Something with syntax you need to transpile? Usually people try to publish ES5 or ES6 in their modules.  You could at least `exclude: "node_modules/core-js/**"`, that takes care of the issue for me.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
