### ISSUE TITLE
named export not detected when typeof operator present and babel external helpers plugin used

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-plugin-commonjs#291]
So, this is a really specific error, but when you have `babel-plugin-external-helpers` present, and you have a typeof operator in a module that is imported using the rollup commonjs plugin, it doesn't detect the named export, even if you specify it in namedExports.

I created a minimal repro here: https://github.com/zwhitchcox/rollup-commonjs-bug

**Comment by edoardocavazza** [comment]
HI @zwhitchcox , have you found a solution?

**Comment by zwhitchcox** [comment]
No, I believe this is still an issue unless someone has fixed it. I am unable to check for a while probably

**Comment by zwhitchcox** [comment]
I think I did find a work around, but I don't remember what it was. It might have been not using require and just using import

**Comment by JedWatson** [comment]
I hit the same issue and resolved it by adding the `externalHelpers: true` option to the `rollup-plugin-babel` config, as mentioned in the docs here: https://github.com/rollup/rollup-plugin-babel#usage

It looks like, for `rollup-plugin-commonjs` to play nicely babel's external helpers plugin, you need to both include the plugin in babel's config **and** set that option:

```
// rollup config
plugins: [
  babel({
    babelrc: false,
    externalHelpers: true,
    presets: [['env', { modules: false }]],
    plugins: [
      'external-helpers',
    ],
  }),
  resolve(),
  commonjs(),
],
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
