### ISSUE TITLE
Default exports can't be found in consumer?

### ISSUE THREAD

**Issue by wldcordeiro** [rollup/rollup-plugin-commonjs#296]
I'm utilizing the library `react-day-picker` in my lib I'm developing. 

I have tried lines like this

```js
import DayPicker from 'react-day-picker/DayPicker'
import { default as DayPicker } from 'react-day-picker/DayPicker'
```

```js
import DayPickerInput from 'react-day-picker/DayPickerInput'
import { default as DayPickerInput } from 'react-day-picker/DayPickerInput'
```

and when I run my lib's storybook those resolve just fine

console.log output
```
function DayPickerInput()
single-picker.js:37
14:19:51.231
function DayPicker()
range-picker.js:159
```

But in the consumer I see this

```
14:25:54.316
Object { default: DayPicker(), DateUtils: {…}, LocaleUtils: {…}, ModifiersUtils: {…}, WeekdayPropTypes: undefined, NavbarPropTypes: undefined, PropTypes: {…}, … }
```

So I'm really not sure what to do at this point. I've tried just about everything and each suggestion I find doesn't work.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
