### ISSUE TITLE
Failing to parse valid JS

### ISSUE THREAD

**Issue by Ottunger** [rollup/rollup-plugin-commonjs#298]
I feel like the plugin cannot parse this file. At version 7.0.0 the error is more verbose though:

```javascript
"use strict";
exports.isArrayLike = (function (x) { return x && typeof x.length === 'number'; });
//# sourceMappingURL=isArrayLike.js.map
```

I get

```txt
[!] Error: Unexpected token
node_modules\rxjs\util\isArrayLike.js (2:78)
1: "use strict";
2: var isArrayLike_1 = function (x) { return x && typeof x.length === 'number'; });
                                                                                 ^
3: //# sourceMappingURL=isArrayLike.js.map
```

If I remove the parenthesis around the function declaration it works.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
