### ISSUE TITLE
Standalone transpilation

### ISSUE THREAD

**Issue by lastmjs** [rollup/rollup-plugin-commonjs#304]
So, I know this plugin is for Rollup, but I could really use the transpilation here standalone. I want to transpile files written in CommonJS to ES Modules, but I don't want any of the bundling to occur. My use cases require runtime resolution of modules using the standard ES Modules syntax and loader. Does anyone have any suggestions? Can this plugin be used standalone? I've gotten into the source code and tried to pull out the functionality that I need, but I ran into some blocking issues with the acorn parser...what would be really awesome is a babel plugin with just the functionality for transpiling CommonJS to ES Modules. Mostly I just want to know if anyone else sees this as a good idea, and for any pointers before I try to do it.

**Comment by lastmjs** [comment]
I think I've found a way to do this using Rollup itself programmatically, which will fit my use case: using the `experimentalPreserveModules` option. It's a very recent addition: https://github.com/rollup/rollup/pull/1922

**Comment by lastmjs** [comment]
It would be really nice to have this plugin do standalone transpilation for a single file though, without walking the dependency tree, dealing with the file system, and all of the extra complications that that is adding as I run into weird edge cases

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
