### ISSUE TITLE
rollup-plugin-commonjs >= 9.0.0 incompatible with rollup-stream

### ISSUE THREAD

**Issue by Mark083** [rollup/rollup-plugin-commonjs#307]
There is a problem when using rollup-plugin-commonjs >= 9.0.0 with rollup-stream as you can see with detail on  [this](https://github.com/Permutatrix/rollup-stream/issues/31) issue

**Comment by martinwebrant** [comment]
Same error with rollupify, The culprit is that they have old versions of rollup as dependencies that does not contain the parse method.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
