### ISSUE TITLE
Transform dynamic require into import?

### ISSUE THREAD

**Issue by eight04** [rollup/rollup-plugin-commonjs#311]
Rollup now supports experimental code splitting/dynamic `import()`. By targetting `format: "cjs"`, it compiles the following code:
```js
import("./foo")
  .then(module => {});
```
into:
```js
Promise.resolve(require("./foo"))
  .then(module => {});
```
For commonjs plugin, maybe it is a good idea to transform `Promise.resolve(require("..."))` into `import("...")` so that rollup can reconize it. This allows people to write working CJS code directly without import-shim etc.

Currently, I use find-and-replace to do the transformation:
https://github.com/eight04/node-test/blob/5d288c60ad0fa7c8c688eb10e8c5030b50725729/rollup.config.js#L13-L14

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by eight04** [comment]
For anyone needs this feature, try https://github.com/eight04/rollup-plugin-cjs-es.
