### ISSUE TITLE
Issue with bundling jss

### ISSUE THREAD

**Issue by caub** [rollup/rollup-plugin-commonjs#317]
I didn't manage to bundle jss (https://github.com/cssinjs/react-jss depends on https://github.com/cssinjs/jss) successfully using rollup

demo repo: https://github.com/caub/rollup-plugin-commonjs-issue
demo live: https://caub.github.io/rollup-plugin-commonjs-issue/index.html

console error: 
```
Uncaught TypeError: (0 , _jss.create) is not a function
    at rollup.js:6240
    at createCommonjsModule (rollup.js:10)
    at rollup.js:6200
```
that create function is exported there: https://github.com/cssinjs/jss/blob/master/src/index.js#L52

I'm not completely sure it's a rollup issue, but webpack works

cc @kof

**Comment by caub** [comment]
after updating a bit react-jss, I have this issue at build time now:
```
> NODE_ENV=production rollup -c


index.js, vendor.js → dist...
[!] Error: 'default' is not exported by ../../../react-jss/lib/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
index.js (3:7)
1: import React from 'react';
2: import ReactDOM from 'react-dom';
3: import injectSheet from 'react-jss';
          ^
4: import Wheel, { OpacityRange } from './src';

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! color-wheel-demo@ build: `NODE_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the color-wheel-demo@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/caub/.npm/_logs/2018-05-03T16_37_39_493Z-debug.log
```

which really appears to be a rollup issue, and particularly this plugin (responsible to import CJS modules)

react-jss src/index default export is this: https://github.com/cssinjs/react-jss/blob/master/src/index.js#L8

transpiled by babel into: https://unpkg.com/react-jss@8.4.0/lib/index.js (the end of)

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
