### ISSUE TITLE
Extending named exports detection

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup-plugin-commonjs#323]
For example for wrappers like - https://github.com/blakeembrey/pluralize/blob/0a9407718092a44abb8e67400ba2371c56576434/pluralize.js

Basically the wrapper itself would need to be some kind of "pattern" that is detected. This seems doable.

Once detected to a common pattern, we should be able to work out which binding references the exports.

Once that is done, we can extend assignment expressions to members of that reference to create named exports.

The hardest part seems to be applying the "wrapper template" correctly, and then expanding that to deal with some variations, but it all seems doable to me.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
