### ISSUE TITLE
Have a 'include' and 'extensions' property,but throw a error message because of a .json file when compiled

### ISSUE THREAD

**Issue by lee-zhi** [rollup/rollup-plugin-commonjs#328]
**Error Message:**

![44](https://user-images.githubusercontent.com/6147874/42626654-75fdcf7c-85fd-11e8-81f9-82c97e22b208.jpg)

**Code:**

![88](https://user-images.githubusercontent.com/6147874/42626696-8c9fb84e-85fd-11e8-9002-7e0a8eeb6ae0.jpg)

**Comment by lukastaegert** [comment]
You need to add `rollup-plugin-json` in order to be able to import JSON files.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
