### ISSUE TITLE
Default import doesn't work with "proxy" file

### ISSUE THREAD

**Issue by MikeTheReader** [rollup/rollup-plugin-commonjs#332]
I'm having an issue importing the default export from a project that uses a "proxy" file to handle the exports. I've created a repo for it, as that was the easiest way to reproduce the whole problem. That repo is at https://github.com/MikeTheReader/rollup-playground and includes a somewhat deeper explanation of what I'm seeing. Basically, it comes down to trying to include a package that uses a file like `module.exports = require("exportedDefault.js");` doesn't import correctly. I'm able to fix this by changing the file to export the object by hand. Something like:

```
const index = require('./index');

module.exports = {
  default: index.default,
  NAMED: index.NAMED,
  __esModule: true
}
```

but the fact that rollup creates the unwrapExports function call, but does nothing with the response from that call leads me to believe there may be a bug that this is tripping.

Thanks for creating a great tool. Please let me know if there's any other information I can provide.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
