### ISSUE TITLE
Can't work with experimentalPreserveModules options

### ISSUE THREAD

**Issue by looch** [rollup/rollup-plugin-commonjs#339]
Can't work with experimentalPreserveModules options, an error is as follows:

> (node:69913) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/Users/c100ng/github/rollupTest/\u0000commonjsHelpers...

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
