### ISSUE TITLE
Pino with rollup

### ISSUE THREAD

**Issue by ansarizafar** [rollup/rollup-plugin-commonjs#342]
I am using rollup-plugin-commonjs in my rollup config but still Pino https://github.com/pinojs/pino is not working. Could someone please show me rollup-plugin-commonjs config for using pino.

**Comment by TrySound** [comment]
@ansarizafar Could you tell what exactly doesn't work? Try to reproduce the problem.

**Comment by ansarizafar** [comment]
I am trying to use pino with sapper. Here is my code from sapper-template (rollup branch)
````
const Pino = require('pino');
const logger =  Pino({
        name: appName,
        level: "info",
       prettyPrint:  true,
        enabled: process.env.NODE_ENV === "production" ? false : true
      });

````
I am getting this error
````
Unexpected token
1: {
2:   "_from": "pino",
            ^
3:   "_id": "pino@5.3.0",
4:   "_inBundle": false,
````

**Comment by TrySound** [comment]
Could you show error stack trace too?

**Comment by ansarizafar** [comment]
I can only see the above mentioned error in terminal, no stack trace. Unfortunately, Sapper is under heavy development so error reporting is not good at the moment.

**Comment by Rich-Harris** [comment]
The unexpected token is coming from inside a JSON file. Do you have rollup-plugin-json installed?

The [browser build of pino](https://unpkg.com/pino@5.4.0/browser.js) doesn't require a JSON file so I assume this is the server build you're talking about, in which case you probably don't need to bundle it anyway.

**Comment by ansarizafar** [comment]
I am using  sapper-template (rollup branch) and rollup-plugin-json is not installed. Yes I am trying to use pino on the server. It seems that the json is from node_module/pino/package.json. No idea why this file is included or How it can be removed from bundle.

**Comment by Rich-Harris** [comment]
You have complete control over the Rollup config; that's why it's exposed to you instead of buried inside the framework. By default, [items in `dependencies` are external](https://github.com/sveltejs/sapper-template/blob/5fa50e0f10474e9286a034fed786f4f8aa748ee0/rollup/server.config.js#L26-L28); perhaps you have pino in `devDependencies`?

Either way, it's trivial to add rollup-plugin-json.

**Comment by ansarizafar** [comment]
pino is not directly installed in sapper template, it is installed in another package under dependencies and that package is installed in sapper-template. I have never used rollup before so no idea how to solve this problem. Do I need to install rollup-plugin-json in sapper-template?

**Comment by Rich-Harris** [comment]
Whatever package depends on pino should be listed in `pkg.dependencies` in your project. Do `npm ls pino` if you're not sure which it is.

> Do I need to install rollup-plugin-json in sapper-template?

Only if you're bundling pino.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
