### ISSUE TITLE
wrong transformation of markdown-it

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup-plugin-commonjs#350]
Hi!

`markdown-it`’s typings are [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/markdown-it/index.d.ts). `require`ing it returns a class:

```js
const MarkdownIt = require('markdown-it')

const md = new MarkdownIt()
md.render(...)
```

However, rollup converts it to this code:

```js
var lib$8 = MarkdownIt;

var markdownIt = lib$8;

var MarkdownIt$1 = /*#__PURE__*/Object.freeze({
	default: markdownIt,
	__moduleExports: markdownIt
});

function myFunc(code) {
	const md = new MarkdownIt$1();
	...
}
```

the problem is that `MarkdownIt$1.default` is the actual class, so `new MarkdownIt$1` fails.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
