### ISSUE TITLE
Duplicate function declarations in non-strict mode should be converted into last

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup-plugin-commonjs#352]
For the following CommonJS code:

```js
function x () { console.log('a') }
function x () { console.log('b') }
x();
```

This will work in CJS non-strict but throw `Identifier 'Prompt' has already been declared` in ES modules under strict mode.

This should be automatically converted into strict mode by this transformer as the following:

```js
function x () { console.log('b') }
x();
```

Since we know that the last declaration will completely override the first.

**Comment by shellscape** [comment]
Hey folks, we've moved this repo to a new home in our plugins monorepo at https://github.com/rollup/plugins. If this issue is still pertinent, please reopen, _by filling out the appropriate issue template_, in the new repo. Thanks for originally opening this issue, and we look forward to seeing you in the new repo. This issue is being closed and this repo is being permanently archived.
