### ISSUE TITLE
Handling try-catch requires

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup-plugin-commonjs#355]
A common pattern in Node.js for detecting if a package is present / optional dependencies is (in eg https://unpkg.com/debug@3.2.6/src/node.js):

```js
var supportsColor;
try {
  supportsColor = require('supports-color');
}
catch (e) {
}
```

It should be possible to support this with the following rule:

1. When a require is within a try block, treat it as an "optional require".
1. Attempt to resolve optional requires using `this.resolve`. If it does, built it in as a dependency.
1. If it does not resolve, do not list it as a dependency at all, and instead replace the require statement with an error that throws:

```js
var supportsColor;
try {
  var e = new Error('Cannot find module \'supports-color\'.');
  e.code = "MODULE_NOT_FOUND";
  throw e;
}
catch (e) {
}
```

Will work on a PR shortly.

**Comment by benmccann** [comment]
It looks to me like the resolution is done at compile time when running roll-up. Is it possible to do it at runtime instead?

Our use case: we're building a chart library called Chart.js and want to give it `peerDependencies` on luxon and moment. If the user wants to plot a time chart they must supply one of these two time libraries. We won't know when compiling Chart.js if the user will be supplying one of these libraries. Instead, it is known only at runtime

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
