### ISSUE TITLE
Does tree shaking works on CommonJS modules? 

### ISSUE THREAD

**Issue by artall64** [rollup/rollup-plugin-commonjs#362]
I have a lot of Node.js(CommonJS) modules that I want a load with rollup-plugin-commonjs plugin.
Does rollup tree shaking is applied to that modules?
I open an issue because can't find the answer anywhere in the docs.
If no - do you have plans to support that?

You also will be glad to see your comment on that [question](https://stackoverflow.com/questions/53349078/how-to-partially-include-node-js-module-using-rollup-with-commonjs-plugin/53363913#53363913) on StackOverflow

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:

**Comment by eight04** [comment]
See https://github.com/eight04/rollup-plugin-cjs-es#comparing-to-rollup-plugin-commonjs
