### ISSUE TITLE
Issue when bundling a module containing winston

### ISSUE THREAD

**Issue by kamleshchandnani** [rollup/rollup-plugin-commonjs#365]
Here's my rollup config
```
export default {
  input: `src/logger.js`,
  external: Object.keys(packageJson.peerDependencies),
  plugins: [
    babel({
      exclude: 'node_modules/**',
      runtimeHelpers: true,
      externalHelpers: true,
    }),
    nodeBuiltIns(),
    commonjs(),
    resolve({ browser: true }),
    json(),
  ],
  output: [{
    file: `logger.js`,
    format: 'esm',
  }, {
    file: `cjs/logger.js`,
    format: 'cjs',
  }],
}
```
And this the `logger.js` file
```
import winston from 'winston'

const logger = winston.createLogger({
  transports: [
    new winston.transports.Console(),
  ],
  exceptionHandlers: [
    new winston.transports.Console(),
  ],
  exitOnError: false,
});

export default logger;
```
now when I import `logger.js` in my projects 
```
import logger from 'utils/logger'

// lambda handler
export const handler = (event, context) => {
  logger.info('handler', { event, context });
};
```
It throws out following error: 
```
[ 'TypeError: Cannot read property \'prototype\' of undefined',
  'at eval (webpack:///../utils/logger.js?:1336:40)',
```

**Comment by evocateur** [comment]
Yeah, this is a circular dependency in `readable-stream` ("intentional", as far as I can tell). The only workaround I've found is to explicitly externalize `readable-stream` so that Rollup never tries to inline it.

**Comment by kamleshchandnani** [comment]
@evocateur Putting `readable-stream` in rollup's `external` didn't work either

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
