### ISSUE TITLE
 createCommonjsModule is not a function when preserveModules is set  'true'

### ISSUE THREAD

**Issue by shrihari-balasubramani** [rollup/rollup-plugin-commonjs#374]
My rollup config looks like this:

```
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import postcss from 'rollup-plugin-postcss';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';

export default {
  input: 'src/components/Button/SomeButton.js',
  output: {
    dir: 'deployed',
    format: 'esm'
  },
  preserveModules: true,
  external: [
    'react'
  ],
  plugins: [
    commonjs({
      include: 'node_modules/**'
    }),  
    resolve({preferBuiltins: false}),      
    json({
      include: 'node_modules/**'
    }),
    babel({
      exclude: 'node_modules/**', // only transpile our source code,
      runtimeHelpers: true
    }),     
    postcss({
      config:false,
      plugins: [],
      extensions: ['.css'],
      extract: false
    })   
  ]
};

````
<img width="1440" alt="screenshot 2019-02-13 at 7 26 39 pm" src="https://user-images.githubusercontent.com/4323322/52717906-32937500-2fc8-11e9-9152-88195383559f.png">

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
