### ISSUE TITLE
Build halts prematurely with no error when module marked as external

### ISSUE THREAD

**Issue by samthor** [rollup/rollup-plugin-commonjs#380]
[Repro here](https://github.com/samthor/rollup-plugin-commonjs-issue), in `repro.js`. Using Rollup 1.7.3 and 9.2.2 of this plugin.

Basically if we mark a (valid) module as external using Rollup like this:

```js
  const bundle = await rollup.rollup({
    input: ['code/test.js'],
    plugins: [rollupPluginCommonJS()],
    external(id, importer, resolved) {
      return true;
    },
  });
```

... then the plugin stops running (similar to #341) so the process halts. (I'm going to try to understand what's going on, but filing a bug first.)

**Comment by lukastaegert** [comment]
Try to exclude modules starting with a `\0` (these are internal to plugins), does this have an effect?

**Comment by samthor** [comment]
Yup, [excluding those](https://github.com/samthor/rollup-plugin-commonjs-issue/blob/master/repro.js#L16) seems to be a workaround.

This generates a `\0commonjs-proxy:...` line but it seems easy (although potentially fragile) just to remove that.

So maybe there's two issues:

1) halting
2) should the `\0commonjs-proxy:...` import be removed (as per my rewriting) when the module is marked as external?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
