### ISSUE TITLE
Memoize function not hoisted in rollup build

### ISSUE THREAD

**Issue by sheuertz** [rollup/rollup-plugin-commonjs#386]
Hi

I'm trying to build a package with rollup v1.7.4 and rollup-plugin-commonjs v9.2.0, but the generated package is not working when I try and import it into a create-react-app typescript app.

A repo with the reproducible packages is available [https://github.com/sheuertz/sample-package-and-app-for-bug](url)

This is the error I'm getting:
![memoize_cjs-error](https://user-images.githubusercontent.com/4041882/55765766-13dcb800-5a26-11e9-940e-7cc168593d45.png)

When I step through with the chrome debugger, memoize_cjs is an object, with a default property, which is the correct function that should be called. I'm unsure if this is an issue with my rollup configuration, or rollup, or this plugin.

Cross posted from [https://github.com/rollup/rollup/issues/2787](url)

**Comment by dglatstein** [comment]
I am also having this error, has anyone been able to find a solution?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
