### ISSUE TITLE
Optimize `module.exports = …` pattern

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup-plugin-commonjs#4]
This is an extremely common pattern used in cjs modules. rollup-plugin-commonjs currently creates suboptimal code for that, see the example from https://github.com/zloirock/core-js/issues/125#issuecomment-152738215:

```js
var exports$198 = {};
var module$198 = { 'exports': exports$198 };
module$198.exports = require$$0$5.document && document.documentElement;

// OR

var exports$129 = {};
var module$129 = { 'exports': exports$129 };
module$129.exports = function(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
};
```

If rollup-plugin-commonjs were a little bit smarter, it could avoid allocating the unused `exports` var/object in that case.
It it were even smarter, it may also be possible to avoid the `modules` map too, but I guess that would depend on the importer side, so it might not be feasible.

**Comment by Rich-Harris** [comment]
It's tricky. There's all sorts of edge cases that are possible with CommonJS, because `module` and `exports` are both just objects that can get renamed and passed around. So it's tricky to determine whether or not `module.exports` is used in cases like this, for example:

```js
function addExportsToModule ( m ) {
  m.exports.foo = 'bar';
}

addExportsToModule( module );
```

A contrived example, perhaps, but I've seen stranger things in the wild.

In 1.1.0, I changed the behaviour such that modules are wrapped in an IIFE, which alleviates the problem a bit – neither `module` nor `exports` are declared, which means you don't end up with `module$129` and `exports$129`. A minifier would get rid of an unnecessary `var exports = module.exports` inside the IIFE.

I like the idea, so it's worth keeping this issue open, but we'd need to be sure we'd accommodated all the cases that could trip up the static analysis.

**Comment by Swatinem** [comment]
I guess this is WONTFIX then along #12…
