### ISSUE TITLE
Faster imports for pre-bundled libraries

### ISSUE THREAD

**Issue by tschaub** [rollup/rollup-plugin-commonjs#41]
I'm hoping to find a way to speed up bundle generation when importing (large) libraries that are pre-bundled as UMD scripts.  When importing a pre-bundled library, there shouldn't be any need to parse the imported script or walk the AST.

Would you suggest creating another plugin for this purpose, or do you think this one could be given an option to skip parsing and AST walking when there are no additional dependencies to resolve?

**Comment by Rich-Harris** [comment]
I like where your head's at. Excuse me while I think aloud. I think it's possibly a bit risky to skip parsing altogether (e.g. the bundle might very will not have any `dependencies` in its package.json, but it might still use modules like `fs` and `path` – without knowing about those requires it's not possible to shim them for use in browser, etc. Plus we need to detect things like `global`, and try to figure out if there are named exports. Also it creates a configuration burden on the user) but I think we probably can speed it up.

The [json](https://github.com/rollup/rollup-plugin-json) plugin has quite a nice trick – it generates a [synthetic AST](https://github.com/rollup/rollup-plugin-json/blob/master/src/index.js#L12-L18) and hands that over to Rollup, which then doesn't need to parse the resulting JavaScript. We could do something similar here, creating a 'black box' whereby Rollup skips the actual module code. That would speed things up considerably by skipping the second parse (one of the shortcomings of the plugin system is that code sometimes has to get parsed more than once).

We then just have the initial parse performed by this plugin. I recently made a package called [tippex](https://github.com/Rich-Harris/tippex) which allows you to robustly identify things like require statements without generating and traversing an AST. It falls over in pathological cases like this...

```js
(function (require) {
  var foo = require('foo');
}(notActuallyRequire));
```

...but as long as no-one does anything that daft, it works well and is an order of magnitude faster than Acorn.

So those two techniques, working together, could drastically improve the performance of this plugin. The downside is that you would no longer get sourcemaps (because they're generated with the help of the correct AST), so it should possibly be behind an option:

```js
plugins: [
  commonjs({ fast: true })
]
```

**Comment by calvinmetcalf** [comment]
you can run it through derequire first to change the internal requires to a different name so this won't find them

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
