### ISSUE TITLE
I try to use Dynamic import syntax and failing as SyntaxError

### ISSUE THREAD

**Issue by qawsedstation** [rollup/rollup-plugin-commonjs#411]
I try to use Dynamic import

`import('index.js').then(pkg => {
  
})`
and failing

I have the latest version of the commonjs rollup plugin 10.1.0

I use Vue.js

**Comment by shellscape** [comment]
@qawsedstation thanks for the issue, but we'll need a _minimal_ repository that demonstrates how to reproduce the issue

We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
