### ISSUE TITLE
Use esnext?

### ISSUE THREAD

**Issue by eventualbuddha** [rollup/rollup-plugin-commonjs#59]
A while ago I started a project to migrate JS from ES5 to ES6 and beyond. One of its plugins is a [CommonJS to ES modules transformer](https://github.com/esnext/esnext/blob/master/src/plugins/modules.commonjs.js). It isn't yet a drop-in replacement for the same logic in this plugin, but it may become so. It'd be nice to have a more general tool that can be the one place to fix issues like #56. I'd like to get other maintainers' thoughts on using it.

**Comment by Rich-Harris** [comment]
No objections from me, if it keeps the existing functionality and makes it easier to maintain. I didn't realise the esnext project was now going the other way! 😜 Looks great. One thing to consider is things like https://github.com/rollup/rollup-plugin-commonjs/issues/41 and other potential optimisations – is esnext accommodating of that sort of hackery?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
