### ISSUE TITLE
What does this suppose to mean ?

### ISSUE THREAD

**Issue by lili21** [rollup/rollup-plugin-commonjs#66]
```
Treating 'crypto' as external dependency
Treating 'net' as external dependency
Treating 'fs' as external dependency
Treating 'tty' as external dependency
```

output bundle file do not work in browser.

my config file

```
import commonjs from 'rollup-plugin-commonjs'
import nodeResolve from 'rollup-plugin-node-resolve'

export default {
  entry: 'index.js',
  format: 'iife',
  plugins: [
    nodeResolve({
      jsnext: true,
      main: true,
      preferBuiltins: false
    }),

    commonjs({
      sourceMap: false,
      ignoreGlobal: true
    })
  ],
  dest: 'napos-ng-analytics.bundle.js'
}

```

**Comment by Victorystick** [comment]
@lili21 Rollup is not able find the requested imports `crypto`, `net`, `fs` and `tty`; and therefore warns you that it must treat them as external. Look into [the Usage options](https://github.com/rollup/rollup-plugin-node-resolve#usage) for the `node-resolve` plugin. Try adding `browser: true` to the config options.

**Comment by lili21** [comment]
Still not working .

```
Treating 'util' as external dependency
No name was provided for external module 'util' in options.globals – guessing 'require$$0'
```

**Comment by StreetStrider** [comment]
I believe this happens because Rollup doesn't do anything special with node's std. Which is OK, but I still want to bundle my code with node's std modules. To solve this issue, Browserify has a special browserifyable twin for every node.js' std module, so when your code requires something like `[path](https://github.com/substack/path-browserify)` or `[stream](https://github.com/substack/stream-browserify)` you will be OK, since it's not depend on IO, so bundle will work even in browser.

Question: how this should be handled with Rollup? should I use browserify collection modules one by one, or there's straightforward solution?

**Comment by TrySound** [comment]
@StreetStrider Rollup is small and fast because it does only necessary things out of the box, not everything we can invent. Every extra feature can be realised like a plugin.
https://github.com/calvinmetcalf/rollup-plugin-node-builtins
List of plugins you can find here https://github.com/rollup/rollup/wiki/Plugins

**Comment by StreetStrider** [comment]
@TrySound, node-builtins is very likely what I need. I will investigate it. Thanks for help.

**Comment by jeffscottward** [comment]
I tried putting in node-builtins but got errors about import/export not being at the top level from my `buble` plugin (Babel but faster)

**Comment by micahscopes** [comment]
For me it ended up being the `preferBuiltins: false` part that made a difference with this error.  I was trying to import math.js.  I was getting `unexpected token: import` in the browser, as well as the `Treating 'util' as external dependency` error.

I did `npm install --save util`, then got warnings about how there were two libraries named `util`, and that I could pick the local one using `preferBuiltins: false`.
