### ISSUE TITLE
Document how files are determined to be CommonJS

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup-plugin-commonjs#88]
it would be great if there was a note in the documentation how `rollup-plugin-commonjs` determines if a file is CommonJS. For example, the fact that the existence of a reference to `globals` causes the file to be interpreted as CommonJS is not super obvious, even if the `package.json` uses `jsnext:main` or `module`.

**Comment by Rich-Harris** [comment]
Yeah, this should be spelled out a bit more clearly. I'd actually be in favour of implementing something along the [unambiguous grammar](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module) proposal – i.e. if there's an `import` or `export` anywhere, it's not CommonJS (and only once we've failed to find `import`/`export` do we look for CommonJS features)

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
