### ISSUE TITLE
How to handle optionalDependencies

### ISSUE THREAD

**Issue by southpolesteve** [rollup/rollup-plugin-commonjs#89]
Using this plugin results in issues when libraries have optional dependencies. Moving over from https://github.com/rollup/rollup-plugin-node-resolve/issues/24 Originally opened by @leeyeh. Quoting them:

``` js
var memcpy = null; try { memcpy = require("memcpy"); } catch (e) {}
if (memcpy) // ...
```

will be rolled to

``` js
var require$$0$2 = _interopDefault(require('memcpy')); // throw
// .....
var memcpy = null; try { memcpy = require$$0$2; } catch (e) {}
if (memcpy) // ...
```

**Comment by TrySound** [comment]
@calvinmetcalf Do you have ideas about it?

**Comment by calvinmetcalf** [comment]
if `_interopDefault(require('memcpy'));` was moved down to the actual point it was retired that would probably do the trick

**Comment by TrySound** [comment]
@Rich-Harris What was the reason to split assignment and requiring?

**Comment by Rich-Harris** [comment]
@TrySound because imports have to be at the top level – there's no way to turn a `require` inside a try-catch into an equivalent import. I think this is just a fundamental difference between CJS and ES. Even if there *were* some way to keep the final `require` call in the same place as the original in the case of CJS bundles, it doesn't work for AMD, UMD etc.

I don't really have any good ideas for this off the top of my head.

**Comment by mbrevda** [comment]
Just saw this in [React-Virtualized](https://github.com/bvaughn/react-virtualized/issues/435). One way to handle this would be introduce some level of support for runtime `require()` calls, where the contents would be pre-hoisted (i.e. calling require would simple execute whatever code would have otherwise been imported).

**Comment by BryanCrotaz** [comment]
I have exactly this issue with `try-thread-sleep`. What's the recommended workaround?

**Comment by bfred-it** [comment]
Related: https://github.com/rollup/rollup/issues/1385

Is this still an issue?
